services:
  # apache activemq-artemis
  artemis:
    image: quay.io/arkmq-org/activemq-artemis-broker:artemis.2.39.0
    container_name: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      - AMQ_USER=artemis
      - AMQ_PASSWORD=artemis
      - AMQ_EXTRA_ARGS=--nio --relax-jolokia